/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prolog;

import RecursosGraficos.RenderTable;
import java.awt.Panel;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URL;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import org.jpl7.Query;
import org.jpl7.Term;

/**
 *
 * @author bryam
 */
public class Ventana extends javax.swing.JFrame implements MouseListener{

    /**
     * Creates new form Ventana
     */
    
    int x, y;
    static Query q1;
    private final ImageIcon icono1=new ImageIcon(getClass().getResource("/RecursosGraficos/icono.png"));
    
    public Ventana(int x1, int y1) {
        x=x1;
        y=y1;
        initComponents();
        String path="consult('v4.pl')";
        q1=new Query(path);
        System.out.println(q1.hasSolution()?"Se logró conectar con prolog":"No se pudo");
        
        
        cargarMatriz(x);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        matriz = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        c2 = new javax.swing.JButton();
        co3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTexto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        matriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        matriz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matrizMouseClicked(evt);
            }
        });
        matriz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matrizKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(matriz);

        jTextField1.setEditable(false);
        jTextField1.setText("Consulta 1: Dar click a cualquier punto");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        c2.setText("Consulta 2");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        co3.setText("Consulta 3");
        co3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co3ActionPerformed(evt);
            }
        });

        tablaTexto.setColumns(20);
        tablaTexto.setRows(5);
        jScrollPane3.setViewportView(tablaTexto);

        jLabel2.setText("VISOR DE CONSULTAS:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(co3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 166, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2)
                    .addComponent(co3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void pressButton(java.awt.event.ActionEvent evt) {                                            
        System.out.println("BOTONMN");
    }
    private void matrizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matrizMouseClicked
        // TODO add your handling code here:
   
    }//GEN-LAST:event_matrizMouseClicked

    private void matrizKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matrizKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_matrizKeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
        String co="c_2_3(0,0,"+x+","+y+",T,S,C,CT, SCT)";
        
        System.out.println("CONSULTA: "+co);
        Query q2=new Query(co);
        int  consulta= Integer.parseInt(q2.oneSolution().get("T").toString());
        Term[]  consulta1= q2.oneSolution().get("S").listToTermArray();
         
        System.out.println("TAMAÑO: "+consulta);
        System.out.println("SIZES: "+consulta1);
        tablaTexto.setText("");
        tablaTexto.setText("RESULTADO CONSULTA 2:\n");
         tablaTexto.append("\nTotal de grupos sin repetir tamaños: "+consulta+"\n");
        int c=1;
        
        while(c<=consulta){
            tablaTexto.append("\nGrupo " +c+": Tamaño: "+consulta1[c-1]);
            c++;
        }
                          
    }//GEN-LAST:event_c2ActionPerformed

    private void co3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co3ActionPerformed
        String co="c_2_3(0,0,"+x+","+y+",T,S,C,CT, SCT)";
        
        System.out.println("CONSULTA: "+co);
        Query q2=new Query(co);
        Term[]  consulta= q2.oneSolution().get("SCT").listToTermArray();
        Term[]  consulta1= q2.oneSolution().get("CT").listToTermArray();
         
        System.out.println("TAMAÑO: "+consulta);
        System.out.println("SIZES: "+consulta1);
        tablaTexto.setText("");
        tablaTexto.setText("RESULTADO CONSULTA 3:\n");
         tablaTexto.append("\nTotal de grupos: "+consulta.length+"\n");
        int c=1;
        
        while(c<=consulta.length){
            tablaTexto.append("\nGrupo " +c+": Tamaño: "+consulta[c-1]
            +"\nCoordenadas:\n"+consulta1[c-1]+"\n");
            c++;
        }
        
    }//GEN-LAST:event_co3ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c2;
    private javax.swing.JButton co3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable matriz;
    private javax.swing.JTextArea tablaTexto;
    // End of variables declaration//GEN-END:variables

    private void cargarMatriz(int tamagno) {
        this.matriz.setDefaultRenderer(Object.class, new RenderTable());
        matriz.setRowHeight(25);
        matriz.addMouseListener(this);
        
        DefaultTableModel modelo=(DefaultTableModel) matriz.getModel();
        modelo.setColumnCount(tamagno);
        modelo.setRowCount(tamagno);
        
        LinkedList<java.lang.Integer[]> casillas=Prolog.crearBase(tamagno, tamagno);
        
        
        for(java.lang.Integer casilla[]: casillas){
            
            if(casilla[2]==1){
               
                String name=casilla[0].toString()+","+casilla[1].toString();
                System.out.println(name);
                JButton bt=new JButton("");
                bt.setIcon(icono1);
                bt.setSize(10, 8);
                
                matriz.setValueAt(bt, casilla[1], casilla[0]);
            }else{
                matriz.setValueAt("", casilla[1], casilla[0]);
            }
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        int fila=matriz.rowAtPoint(e.getPoint());
        int colum=matriz.columnAtPoint(e.getPoint());
        
        consulta1(colum, fila);
    }
    
    private void consulta1(int x, int y){
        String co="c1("+x+","+y+",N,Coords)";
        Query q2=new Query(co);
        String  consulta= q2.oneSolution().get("N").toString();
        String  consulta1= q2.oneSolution().get("Coords").toString();
         
        System.out.println("TAMAÑO: "+consulta);
        System.out.println("COORDS: "+consulta1);
        tablaTexto.setText("");
        tablaTexto.setText("""
                           RESULTADO CONSULTA 1:
                           Casilla consultada: ("""+x+", "+y+")\n"
                        + "Tamaño del grupo: "+consulta);
    }
    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
       
    }

}
